### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by htanh034** [shaikhsp33r/opencore-dell-3567-hackintosh#1]
Please Update guide Big Sur. tsk!

**Comment by mdadsh** [comment]
My current plan is to get everything working as close to as original MacBooks on Catalina then move on to major OS release. That said, I'll start working on Big Sur pretty soon.

**Comment by mdadsh** [comment]
Upgrade to Big Sur:

1. Download OpenCore 0.6.3 and OcBinaryData
2. Make changes in plist as per changelog (config.plist is in EFI folder for reference)
3. Mount EFI partition and replace the EFi folder.
3. Start and upgrade from Software Update from Settings.

Make sure the changes in the plist are as per my plist file or else the Wi-Fi will stop working post upgrade.
